# Generated by Django 5.2.10 on 2026-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('sistema', models.CharField(max_length=100)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en proceso', 'En proceso'), ('espera información', 'Espera información'), ('pendiente confirmación', 'Pendiente confirmación'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=25)),
                ('descripcion', models.TextField()),
                ('procesos', models.TextField(blank=True, default='')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=20)),
                ('evidencia', models.JSONField(blank=True, default=list)),
                ('conversacion', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
